### ISSUE TITLE
Feature request, Please consider supporting command line parameters , If there are parameters, the first parameter is the book file name.

### ISSUE THREAD

**Issue by rango886** [chrox/readest#4] opened 2024-12-02 14:24 UTC
Such a function is very useful !!!
1. Under the Windows operating system, you can set Readest as the default program to open files. If you set Readest as the default program for opening EPUB files, then you can double-click any EPUB file to open it with Readest. The current version doesn't support command-line parameters, When you set Readest as the default program for opening EPUB files, it will open the start interface of the program instead of the reading interface. (The principle of double-clicking to open a file with the default program under Windows is to pass the file path of the file to be opened as the first command-line parameter to the default program for this kind of file.)
2. It is command-line friendly. You can directly use Readest from the command line to open the specified book files.

**Comment by chrox** [comment] 2024-12-02 14:31
Yes, this feature is planned and will be implemented very soon.

**Comment by chrox** [comment] 2024-12-03 21:19
Implemented in https://github.com/chrox/readest/commit/1429f111bce7c3af0fa0cb5d8c36de77eaaca707. Only tested on macOS. Could you help me to test this feature on Windows?

**Comment by rango886** [comment] 2024-12-04 01:50
Okay, I'll give it a try

**Comment by rango886** [comment] 2024-12-04 03:31
https://github.com/chrox/readest/commit/1429f111bce7c3af0fa0cb5d8c36de77eaaca707  Not work, It will get stuck after starting in the way of passing parameters.

![NVIDIA_Share_XDBaGOPoPl](https://github.com/user-attachments/assets/6235f218-9bf8-42e8-a31e-334de1875e53)

**Comment by chrox** [comment] 2024-12-04 07:16
> https://github.com/chrox/readest/commit/1429f111bce7c3af0fa0cb5d8c36de77eaaca707  Not work, It will get stuck after starting in the way of passing parameters.
> 
> 

What does the console log in the dev tool say? If there is no log you need to show the dev tool at app start by commenting [this line](https://github.com/chrox/readest/blob/main/apps/readest-app/src-tauri/src/lib.rs#L112) and uncommenting the following two lines.

**Comment by rango886** [comment] 2024-12-04 08:57
403 error, Administrator privileges also don't work, but the file does exist, and I can pass the parameters normally with https://github.com/rango886/foliate-electron


![image](https://github.com/user-attachments/assets/926f2e0b-9a4f-4a5c-9d95-9bec1abf1462)

**Comment by chrox** [comment] 2024-12-04 09:00
I see. It's file scope issue of access permission from tauri. I will take a look.

**Comment by chrox** [comment] 2024-12-04 12:50
Currently readest has an asset protocol scope with this:
```
"assetProtocol": {
        "enable": true,
        "scope": {
          "allow": ["$RESOURCE/**", "$DOCUMENT/**/*", "$APPDATA/**/*", "$TEMP/**/*"],
          "deny": []
        }
      }
```
It means by default only files in these directory can be accessed by Readest, unless user explicitly select the files in other locations in a file open dialog which will be expanded to the file scope at runtime by tauri. You can verify this by open a document in user Document directory with command line interface.

The strange thing is that we have already expand the file scope for the files from cli arguments: https://github.com/chrox/readest/blob/main/apps/readest-app/src-tauri/src/lib.rs#L84-L85

It might by some bug in Tauri since it works in macOS. I'll look into this further.

**Comment by chrox** [comment] 2024-12-04 17:40
Fixed in https://github.com/chrox/readest/commit/999e4828dbbc43646c7ff4392030fe06cab571b0. Not a bug in Tauri code. 😆

**Closed** 2024-12-04 17:41 UTC
